/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonbutton: typeof import('element-plus/es')['ElButtonbutton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InputIcon: typeof import('./src/components/InputIcon.vue')['default']
    Rem: typeof import('./src/components/Rem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechRecognition: typeof import('./src/components/SpeechRecognition.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TeacherCard: typeof import('./src/components/TeacherCard.vue')['default']
    VoiceEndIcon: typeof import('./src/components/VoiceEndIcon.vue')['default']
    VoiceIcon: typeof import('./src/components/VoiceIcon.vue')['default']
    VoiceStartIcon: typeof import('./src/components/VoiceStartIcon.vue')['default']
    VoiceStopIcon: typeof import('./src/components/VoiceStopIcon.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
  }
}
